source: .
destination: _site
includes_dir: _includes
baseurl: ""

include:
  - _data

url: "https://feizhao19.github.io"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - markdown_generator
  - talkmap
  - vendor
  - _pages
  - _posts
  - _sass
  - _teaching
  - _portfolio
  - _drafts
  - _website_2014
  - assets/css
  - assets/js
  - node_modules
  - package.json
  - _layouts/minimal-mistakes-default.html
  - _layouts/archive.html
  - _layouts/archive-taxonomy.html
  - _layouts/compress.html
  - _layouts/profile.html
  - _layouts/single.html
  - _layouts/splash.html
  - _layouts/talk.html
